### ISSUE TITLE
update howto page

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#13]
contains old links and images

**Comment by denjello** [comment]
http://beta.leerstandsmelder.de/site/howto

**Comment by dasantonym** [comment]
can you write this up in english and add pictures? just edit the markdown file in ``shared/static/md``and add assets in ``assets/images/`` (these are copied into ``/images`` when ``gulp web`` runs. i'll do the german version if you don't have time.

**Comment by denjello** [comment]
Working on this right now. Will create a German version with my terrible German style.
