### ISSUE TITLE
geosearch does not trigger update handler

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#16]
it does not move the marker but instead creates a new non-draggable marker

**Comment by denjello** [comment]
do you mean when creating a new location?

**Comment by denjello** [comment]
The geosearch bar that used to be in the map?

**Comment by dasantonym** [comment]
yeah, it does nothing to remind the controller to update all the things on the page (address form, marker object...)

**Comment by denjello** [comment]
then let's leave this as a won't fix and get on with other issues.
