### ISSUE TITLE
translate form issue

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#19]
this is a long-standing issue with the translate module and its integration with material design. Here is a solution:

https://github.com/angular/material/issues/1742#issuecomment-194200104

**Comment by dasantonym** [comment]
what exactly is the issue you are referring to?

this one? https://github.com/Leerstandsmelder/leerstandsmelder-angular-frontend/blob/master/src/shared/js/controllers/widgets.js#L12-L16

**Comment by denjello** [comment]
This too has been resolved.
