### ISSUE TITLE
search engine compatibility

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#2]
as of now the site is not indexable so i added a module to support phantomjs rendering of static pages for the url-fragment indexing method.

one problem remains: there are no links pointing to the regions and the locations. only user triggered actions can lead you there so what about the robots?

@denjello maybe you can give some input on this one?

**Comment by denjello** [comment]
I liked the idea about including footer links to api results / perhaps by city.

**Comment by dasantonym** [comment]
there was only one out-of-the-box-solution for this that worked and captured all our pages without any code modifications: https://www.seo4ajax.com/

so i'd recommend buying a monthly commitment plan until we manage to set up our own snapshot service. at the moment we are limited to 1000 pages and 5000 updates per month (free plan)
