### ISSUE TITLE
Firstload of Homepage News is not loaded until action

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#21]
until the user clicks / interacts with something, the sidebar is not loaded.

**Comment by dasantonym** [comment]
can't reproduce, needs more info!

**Comment by dasantonym** [comment]
is this still an issue? i haven't seen this on any of the test setups yet.

**Comment by denjello** [comment]
It was an issue in Firefox, but now it is working fine and as expected.
