### ISSUE TITLE
table sort is acting weird

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#23]
results move around randomly in the list
https://beta.leerstandsmelder.de/users/me/locations

md-data-table should be updated within the next days, new version is out just now, but breaks table selection (at the very least)

might also be api related, need to investigate

**Comment by denjello** [comment]
is this still happening?

**Comment by dasantonym** [comment]
yes but now that seems to be something related to the api (worst case is a combination of both)

**Comment by Sefux** [comment]
md-data-table was removed and ag-grid was added.
