### ISSUE TITLE
get a subscription for seo4ajax on a gv account

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#28]
i'll fork over the first month to get this up and running faster.

https://www.seo4ajax.com/

**Comment by denjello** [comment]
ok - which one? project or growth?

**Comment by dasantonym** [comment]
project, but monthly commitment. is there a gv cc readily available? if not i'll front the first one because we need to get the account tonight.

**Comment by denjello** [comment]
No - there isn't, unfortunately.

**Comment by dasantonym** [comment]
no problem, i'll sign up and we'll sort this out later

**Comment by dasantonym** [comment]
done
