### ISSUE TITLE
scrollable frames for lists

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#3]
@denjello can you do me a solid and turn those recent activity lists (one in the dataviewer, one under the shared folder) into frames that go full height and are scrollable?

**Comment by denjello** [comment]
On the top of my todo.

**Comment by dasantonym** [comment]
does not properly scroll on chrome yet, ff seems ok

see https://github.com/angular/material/issues/2454

**Comment by dasantonym** [comment]
in chrome it seems the height of the toolbar adds to the 100% height of the css hack

**Comment by dasantonym** [comment]
worksforme
