### ISSUE TITLE
provide better overview for recent updates

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#31]
we need to improve the findability of new updates on the site (globally across regions, but also within a region)

**Comment by denjello** [comment]
can you be more clear. i am not sure what "findability means". 

one suggestion i heard was to have pictures of the newest "leerstand" in a scroller at the top of the landing page...

**Comment by dasantonym** [comment]
"ability to find stuff" would come closest to this made up word, i guess. at the moment there is no way you can see what's happening in all regions in an overview and the regions can only show the most recent ten.

**Comment by Sefux** [comment]
done. theere is a new admin / region editor interface with sortable tables, search etc.
