### ISSUE TITLE
region slug undefined during first search

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#36]
I searched for "Daniel" in the searchbox, clicked on the only result and landed here:

https://www.leerstandsmelder.de/undefined/daniel-bartels-hof-4e682

it seems that the region slug is not being defined via the search...

**Comment by dasantonym** [comment]
now fixed. i forgot to implement the slug output in the api. also now averting an exception in the frontend when the item in the change handler is undefined
