### ISSUE TITLE
Osnabrueck is not Hamburg...

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#43]
https://leerstandsmelder.de/osnabrueck/landhaus-mahr-92419

Maybe we need to run through all of the assets that we took over and make sure that they are attributed to the right place. On a sidenote, the region slug in the URL does not really appear to do much of anything, except give some visual / textual feedback about where one is...

![osnabrueck](https://cloud.githubusercontent.com/assets/6129121/15161056/efaa16ea-16fc-11e6-942b-c2cc339711c5.jpg)

**Comment by dasantonym** [comment]
the region slug was initially only for seo but then i hooked it up to the navbar controller (i think) so maybe it is just not updating anymore? could it be that you were on osnabrück before going to this page?

**Comment by Sefux** [comment]
can not reproduce.
