### ISSUE TITLE
image sizes

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#46]
I have noticed that there are some images of the leerstand that are just plain huge. Like 4 mb etc... 

for example: 

https://leerstandsmelder.de/berlin/raw-gelaende-f35b6

It might be a good idea to go through the storage and crush them down to size. We fdon't need to be serving that cruft - and it will definitely slow down mobile / eat their mobile traffic. Dumb question: How are uploads handled on the backend at the moment?

**Comment by Sefux** [comment]
there is now a lightbox like popup which only shows the thumbnails on the detail page.
