### ISSUE TITLE
Leerstand Create → Details → Building Type needs an "other" type

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#49]
This is pretty commonly used by the people, so we need to add another field to the list.
- Other / Andere

that when selected then opens an input field where they can add a new type. For bonus points it should be an autocomplete. 

Of course this will be a problem because we won't have it in both languages, so ultimately this is really a huge dumb can of worms. :(

**Comment by Sefux** [comment]
Building type "other" was added. 
But the list should not get bigger (because of easy catgorisation), so until now there will be no input field.
