### ISSUE TITLE
responsive layout

### ISSUE THREAD

**Issue by dasantonym** [Leerstandsmelder/leerstandsmelder-angular-frontend#5]
the layout must become responsive in order to be ready for the mobile app. can you check what needs to be done?

**Comment by denjello** [comment]
this will require adding breakpoints according to material design specs. will do.

**Comment by dasantonym** [comment]
this is super important right now so we can finally go into testing with the app

**Comment by denjello** [comment]
Closing because of added breakpoints and fixed menu.
