### ISSUE TITLE
All comments (and images?) are being loaded for individual leerstände

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#50]
It seems that on every page load like at

https://leerstandsmelder.de/goerlitz/hilgerstrasse-buerobau-6753f

all comments from all assets are being dropped in and all images? (not sure but it is a lot of them) are also seem to be loaded. Of course this has an impact on the loading time of the asset.

(The first comment here is actually older than the post itself...)

![everything_at_once](https://cloud.githubusercontent.com/assets/6129121/15604474/e99d8dde-2400-11e6-8940-5c75e2c72476.png)

**Comment by dasantonym** [comment]
this is now fixed. the data itself is still intact, it was "only" a bug in the api resource query mapping. i had to purge purge api keys and access tokens in the process so if anyone lost any scopes, let me know.
