### ISSUE TITLE
Asset Editing

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#51]
- [x] 1. Fix the free-text field (for Building Type) → Other + free text
- [x] 2. Abgerissen Einstellung
- [x] 3. Delete Asset (in case it is just wrong: e.g. Rathaus Hamburg)
- [x] 4. Enable the Admin / Owner to delete comments, images
- [x] 5. Show Images on the Overview page

**Comment by Sefux** [comment]
done
