### ISSUE TITLE
Integrate Prunecluster

### ISSUE THREAD

**Issue by denjello** [Leerstandsmelder/leerstandsmelder-angular-frontend#6]
This should definitely speed up the display of hundreds of nodes.

**Comment by dasantonym** [comment]
crucial for the app launch, we need this asap!

**Comment by denjello** [comment]
this maybe:

https://www.mapbox.com/blog/supercluster/

**Comment by denjello** [comment]
i looked at supercluster, and it seems to be a pain to implement. as i have some experience already with prunecluster I will implement that.

**Comment by Sefux** [comment]
leaflet.markercluster was added to implement clustering of nodes.
